// Generated by CoffeeScript 1.9.0
(function() {
  module.exports = {
    'output-homes': ['/Volumes/Storage/archive', '/Volumes/da bin ich', '/Volumes/mercury/archive', '/Volumes/hier ist er'],
    'archive-format': 'UDRW',
    'max-backup-count': 3
  };

}).call(this);
