// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    'output-homes': ['/Volumes/Storage/__NEW__', '/Volumes/da bin ich', '/Volumes/da ist er'],
    'archive-format': 'UDBZ'
  };

}).call(this);
